POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "Lauri Leppänen",
  "dateOfBirth": "1298-03-16",
  "ssn": "115627-235T",
  "gender": "male",
  "occupation": "Software developer"  
}